version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: onion_prices_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: onion_prices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d onion_prices"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: onion_prices_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
    driver: local
